#!/usr/bin/env bash
# gha-findroot -- find the root of the current github analysis repository
# Usage: gha findroot
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

OPWD=$PWD

is-root() { [ -d .gha ]; }

while ! is-root && [ "$PWD" != / ]; do
    cd ..
done

if is-root; then
    pwd
else
    error "$OPWD: Not inside an experiment repository"
fi
