#!/usr/bin/env bash
# sagh-findroot -- find the root of the current GitHub analysis repository
# Usage: sagh findroot
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-14
set -eu

OPWD=$PWD

is-root() { [ -d .sagh ]; }

while ! is-root && [ "$PWD" != / ]; do
    cd ..
done

if is-root; then
    pwd
else
    error "$OPWD: Not inside a SAGH repository"
fi
