#!/usr/bin/env bash
# compute-common-files -- compute the number of common files between contributors from git log
# Usage: sagh compute common-files
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-15
set -eu

export LC_ALL=C

cd git
git log --format="Author: %ae" --stat |
python "$TOOLSDIR"/DF-graphCreate.py
