#!/usr/bin/env python
import networkx as nx
import sagh,sys
import re
import pickle

g = nx.Graph()

graphFileName = sagh.suffixWithArgs('user-file-graph', 1)

# load subgraphs into a global graph
def loadSubgraph(repo):
    subg = pickle.load(open(sagh.fileFor(graphFileName)))
    print >>sys.stderr, repo, subg.number_of_nodes(), subg.number_of_edges()
    def prefix(n,d=None):
        if d == None:
            d = subg.node[n]
        if "type" in d:
            if d["type"] == "File":
                return "%s/%s" % (repo, n)
            else: # "Developer"
                return n
        else:
            raise Exception("No type for %s: %s" % (repo, n))
    # copy all the nodes by prefixing ids
    for n,d in subg.nodes_iter(data=True):
        gn = prefix(n, d)
        g.add_node(gn, d)
    # copy all the edges
    for n,n2,d in subg.edges_iter(data=True):
        gn  = prefix(n)
        gn2 = prefix(n2)
        g.add_edge(gn, gn2, d)
    print >>sys.stderr, repo, " copied"
sagh.for_each_repo(loadSubgraph)

intg = nx.convert_node_labels_to_integers(g, discard_old_labels=False)
intg.node_labels_inv = {intid:name for name, intid in intg.node_labels.items()}

pickle.dump(intg, open(graphFileName, "w"))
