#!/usr/bin/env bash
# for-each-repo -- run given command inside each repo
# Usage:   for-each-repo COMMAND [ARG]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-14
set -eu

[ $# -gt 0 ] || usage "$0" "COMMAND missing"

: ${SAGH_NUMCORES:=$(grep -c 'processor.*:' /proc/cpuinfo || echo 1)}
: ${SAGH_ROOT:=$(sagh-findroot)}
export SAGH_ROOT
cd "$SAGH_ROOT"

mkdir -p computed
cd computed

cat ../repos.txt | # from repos.txt
sed 's/[ \t]*#.*$//' | grep -v '^\s*$' | # remove all comments
xargs --max-procs=$SAGH_NUMCORES -I"{}" -- bash -c '
repo={}
mkdir -p "$repo"
cd "$repo"
GITHUB_REPO="$repo" \
GIT_DIR="$SAGH_ROOT/github/$repo/git" \
    "$@"
' -- "$@" # and run in parallel
