#!/usr/bin/env bash
# for-each-repo -- run given command inside each repo
# Usage:   for-each-repo COMMAND [ARG]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-14
set -eu

[ $# -gt 0 ] || usage "$0" "COMMAND missing"

: ${SAGH_ROOT:=$(sagh-findroot)}
export SAGH_ROOT

for repo in $(cat repos.txt); do
    (
    mkdir -p "computed/$repo"
    cd "computed/$repo"
    GIT_DIR="$SAGH_ROOT/github/$repo/git" \
    GITHUB_REPO=$repo \
        "$@"
    )
done
