#!/usr/bin/env bash
# jsonpath -- run JSONPath on STDIN
# Usage: jsonpath QUERY <JSONINPUT
# See: http://goessner.net
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-15
set -eu

[ $# -eq 1 ] || usage "$0" "JSONPath QUERY missing"

query=$1; shift

coffee -e '
JSONPath = require "JSONPath"
obj = JSON.parse(require("fs").readFileSync("/dev/stdin").toString())
path = process.argv[4]

for e in JSONPath.eval(obj, path)
    console.log if typeof e == "object" then JSON.stringify e else e
' "$query"
