#!/usr/bin/env bash
# sagh-compute -- compute a global graph property on GitHub repos
# Usage: sagh compute GLOBAL_PROPERTY [ARG]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-14
set -eu

[ $# -gt 0 ] || {
    usage "$0" "GLOBAL_PROPERTY missing" || true
    msg
    cd "$TOOLSDIR"
    msg "GLOBAL_PROPERTY must be one of:"
    for prop in compute-global-*; do
        [ -x "$prop" ] || continue
        msg "  ${prop#compute-global-}"
    done
    false
}

: ${SAGH_ROOT:=$(sagh-findroot)}

globalProperty=$1; shift

# postfix output file with arguments
suffix=; for arg; do suffix+="-$arg"; done

cd "$SAGH_ROOT"

cmd="compute-global-$globalProperty"

if ! type "$cmd" &>/dev/null; then
    error "$globalProperty: Undefined global property"
else
    # run the script and store the result
    mkdir -p computed
    cd computed
    out="$globalProperty$suffix.txt"
    run -o "$out"   "$cmd" "$@"
    # remove empty output, assuming $cmd created its own
    [ -s "$out" ] || rm -f "$out"
fi
