#!/usr/bin/env bash
# sagh-timed -- prefix stdout/err with timestamps
# Usage: sagh timed COMMAND [ARG]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-12-06
set -eu

[ $# -gt 0 ] || usage "$0" "COMMAND missing"

"$@" 2>&1 |
while read -r line; do
    echo $(date +"%F %T.%N") $'\t' "$line"
done
