#!/usr/bin/env bash
# sagh-compute-each -- compute a property for each GitHub repo
# Usage: sagh compute-each LOCAL_PROPERTY [ARG]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-14
set -eu
shopt -s extglob

[ $# -gt 0 ] || {
    usage "$0" "LOCAL_PROPERTY missing" || true
    msg
    cd "$TOOLSDIR"
    msg "LOCAL_PROPERTY must be one of:"
    for prop in compute-each-*; do
        [ -x "$prop" ] || continue
        msg "  ${prop#compute-each-}"
    done
    false
}

[ -n "${SAGH_ROOT:-}" ] || SAGH_ROOT=$(sagh-findroot)

localProperty=$1; shift

cd "$SAGH_ROOT"

cmd="compute-each-$localProperty"

if ! type "$cmd" &>/dev/null; then
    error "$localProperty: Undefined local property"
else
    for-each-repo compute-each "$localProperty" "$@"
fi
