#!/usr/bin/env bash
# sagh-view -- view a Python pickled data
# Usage: sagh view PICKLED_DATA_FILE
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-12-07
set -eu

[ $# -gt 0 ] || usage "$0" "PICKLED_DATA_FILE missing"

: ${PAGER:=less}

python -c '
import sys,pickle
from pprint import pprint
def show(x): print json.dumps(x, sort_keys=True, indent=1)
def show(x): pprint(x)
show(pickle.load(open(sys.argv[1])))
' "$@" | $PAGER
