#!/usr/bin/env bash
# sagh-compute-global -- compute a global graph property on GitHub repos
# Usage: sagh compute-global GLOBAL_PROPERTY [ARG]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-14
set -eu

[ $# -gt 0 ] || usage "$0" "GLOBAL_PROPERTY missing"

: ${SAGH_ROOT:=$(sagh-findroot)}

globalProperty=$1; shift

cd "$SAGH_ROOT"

cmd="compute-global-$globalProperty"

if ! type "$cmd" &>/dev/null; then
    error "$globalProperty: Undefined global property"
else
    # run the script and store the result
    mkdir -p computed
    out="computed/$globalProperty.txt"
    "$cmd" "$@" | tee "$out"
    # remove empty output, assuming $cmd created its own
    [ -s "$out" ] || rm -f "$out"
fi
