#!/usr/bin/env bash
# githubapi -- use GitHub API from command-line
# Usage: githubapi [VERB] RESOURCE [CURL_OPTS]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-15
set -eu

[ $# -gt 0 ] || usage "$0" "RESOURCE missing"

resource=$1; shift

: ${GITHUB_USER:=$(git config github.user)}
: ${SAGH_ROOT:=$(sagh-findroot)}

cd "$SAGH_ROOT"

githubAPITokenFile=.sagh/githubapi-token
while api_token=$(cat $githubAPITokenFile 2>/dev/null); [ -z "$api_token" ]; do
    # TODO check if token works
    curl -s --user $GITHUB_USER -H "Content-Type: application/json" \
        -d '{ "note":"sagh", "note_url":"https://github.com/netj/sagh" }' \
        https://api.github.com/authorizations |
    jsonpath "$.token" >$githubAPITokenFile
done


curl -s -H "Authorization: token $api_token" \
    https://api.github.com$resource \
    "$@"
