#!/usr/bin/env bash
# sagh-ls-repos -- list repos of a github user
# Usage: sagh ls-repos USER
# 
# This will output REPO\tNUMSTARS\tNUMFORKS for each repository of the USER.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-15
set -eu

[ $# -gt 0 ] || usage "$0" "GITHUB_REPO missing"

user=$1; shift

# normalize $user
user=${user#http://}
user=${user#https://}
user=${user#github.com/}
userurl=https://github.com/$user

jquery $userurl '
$(".repo-stats").each ->
    t = $(this)
    num = ((sel) -> t.find(sel).text().trim().replace(/,/g,""))
    print [t.parent().find(".fork-flag, h3").last().find("a").attr("href").substring(1),
        num(".stargazers"), num(".forks")].join "\t"
' | sort -n -r -k3
