#!/usr/bin/env bash
# sagh-sync-repos -- clone repos from GitHub or update them
# Usage:   sagh sync-repos
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-14
set -eu

for-each-repo sh -c '
    msg -2 "Syncing $GITHUB_REPO"
    ln -sfn "$GIT_DIR" git
    if ! [ -s git/HEAD -o -s git/.git/HEAD ]; then
        mkdir -p "$(dirname "$GIT_DIR")"
        git clone --bare "https://github.com/$GITHUB_REPO.git" "$GIT_DIR"
    fi
    cd git
    git remote update
    '
